apiVersion: apps/v1
kind: Deployment
metadata:
  name: crimeapi
  labels:
    app: crimepi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crimeapi
  template:
    metadata:
      labels:
        app: crimeapi
    spec:
      containers:
      - name: crimeservice
        image: crimeservice
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crimeservice
spec:
  selector:
    app: crimeapi
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
