apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificator
  labels:
    app: notificator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificator
  template:
    metadata:
      labels:
        app: notificator
    spec:
      containers:
      - name: notificator
        image: reportmail
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 5672
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notificatorservice
spec:
  selector:
    app: notificator
  type: LoadBalancer  
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - name: rabbitmq-amqp-port
      protocol: TCP
      port: 5672
      targetPort: 5672
